grails:
    profile: plugin
    codegen:
        defaultPackage: com.dc

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'